{
 "title": "Energy",
 "time": { "from": "2024-03-12T09:21:04.268Z", "to": "2024-03-12T09:26:12.647Z" },
 "templating": {
  "list": [
   {
    "name": "platform_name",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance-carina\",\n    tag: \"platform_name\",\n    predicate: (r) => true,\n    start: -30d,\n)"
   },
   {
    "name": "os_version",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance-carina\",\n    tag: \"os_version\",\n    predicate: (r) => r[\"platform_name\"] == \"${platform_name}\",\n    start: -30d,\n)"
   },
   {
    "name": "device_name",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance-carina\",\n    tag: \"device_name\",\n    predicate: (r) => r[\"os_version\"] == \"${os_version}\",\n    start: -30d,\n)"
   },
   {
    "name": "flow_id",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance-carina\",\n    tag: \"flow_id\",\n    predicate: (r) => r[\"device_name\"] == \"${device_name}\",\n    start: -30d,\n)"
   }
  ]
 },
 "panels": [
  { "title": "Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cost",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cost\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    },
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cost\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn:(r) => r[\"element_name\"] != \"\")"
    }
   ]
  },
  {
   "title": "Cost Range",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"display_cost\" or r[\"_field\"] == \"cpu_cost\" or r[\"_field\"] == \"appState_cost\" or r[\"_field\"] == \"gpu_cost\" or r[\"_field\"] == \"location_cost\" or r[\"_field\"] == \"networking_cost\" or r[\"_field\"] == \"thermalState_cost\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Total display cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"display_cost\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Total CPU cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_cost\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Total appstate cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"appState_cost\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Total GPU cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_cost\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Total location cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"location_cost\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Total net cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"networking_cost\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Total thermalState cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"thermalState_cost\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Total cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_cost\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])\n  \n"
    }
   ]
  },
  { "title": "Overhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Overhead",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_overhead\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    },
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_overhead\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn:(r) => r[\"element_name\"] != \"\")"
    }
   ]
  },
  {
   "title": "Energy overhead range",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"appState_overhead\" or r[\"_field\"] == \"cpu_overhead\" or r[\"_field\"] == \"display_overhead\" or r[\"_field\"] == \"location_overhead\" or r[\"_field\"] == \"networking_overhead\" or r[\"_field\"] == \"gpu_overhead\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    }
   ]
  },
  {
   "title": "Total display overhead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"display_overhead\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    }
   ]
  },
  {
   "title": "Total CPU overhead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_overhead\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    }
   ]
  },
  {
   "title": "Total appState overhead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"appState_overhead\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    }
   ]
  },
  {
   "title": "Total GPU overhead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_overhead\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    }
   ]
  },
  {
   "title": "Total location overhead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"location_overhead\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    }
   ]
  },
  {
   "title": "Total net overhead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Energy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"networking_overhead\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])\n"
    }
   ]
  }
 ]
}