{
 "title": "Graphics",
 "time": { "from": "2024-03-11T09:14:17.272Z", "to": "2024-03-11T09:15:12.997Z" },
 "templating": {
  "list": [
   {
    "name": "platform_name",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance\",\n    tag: \"platform_name\",\n    predicate: (r) => true,\n    start: -30d,\n)"
   },
   {
    "name": "os_version",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance\",\n    tag: \"os_version\",\n    predicate: (r) => r[\"platform_name\"] == \"${platform_name}\",\n    start: -30d,\n)"
   },
   {
    "name": "device_name",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance\",\n    tag: \"device_name\",\n    predicate: (r) => r[\"os_version\"] == \"${os_version}\",\n    start: -30d,\n)"
   },
   {
    "name": "flow_id",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance\",\n    tag: \"flow_id\",\n    predicate: (r) => r[\"device_name\"] == \"${device_name}\",\n    start: -30d,\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Core Animation Frames Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"performance\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Graphics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FPS\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"performance\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Graphics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FPS\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn:(r) => r[\"element_name\"] != \"\")"
    }
   ]
  },
  {
   "title": "GPU Utilization (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Graphics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_utilization\" or r[\"_field\"] == \"renderer_utilization\" or r[\"_field\"] == \"tiler_utilization\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])\n"
    }
   ]
  },
  {
   "title": "Tiled scene bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"performance\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Graphics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tiled_scene_bytes\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> group(columns:[\"device_name\"])\n  |> drop(columns:[\"element_name\"])"
    },
    {
     "query": "from(bucket: \"performance\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Graphics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tiled_scene_bytes\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn:(r) => r[\"element_name\"] != \"\")"
    }
   ]
  }
 ]
}