{
 "title": "Netstat",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "platform_name",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance-carina\",\n    tag: \"platform_name\",\n    predicate: (r) => true,\n    start: -30d,\n)"
   },
   {
    "name": "os_version",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance-carina\",\n    tag: \"os_version\",\n    predicate: (r) => r[\"platform_name\"] == \"${platform_name}\",\n    start: -30d,\n)"
   },
   {
    "name": "device_name",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance-carina\",\n    tag: \"device_name\",\n    predicate: (r) => r[\"os_version\"] == \"${os_version}\",\n    start: -30d,\n)"
   },
   {
    "name": "flow_id",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"performance-carina\",\n    tag: \"flow_id\",\n    predicate: (r) => r[\"device_name\"] == \"${device_name}\",\n    start: -30d,\n)"
   }
  ]
 },
 "panels": [
  { "title": "Process netstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Net bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat_pid\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rb\" or r[\"_field\"] == \"tb\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Net packets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat_pid\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rp\" or r[\"_field\"] == \"tp\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Network bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat_pid\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rb\" or r[\"_field\"] == \"tb\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat_pid\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rb\" or r[\"_field\"] == \"tb\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn:(r) => r[\"element_name\"] != \"\")"
    }
   ]
  },
  {
   "title": "Network packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat_pid\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rp\" or r[\"_field\"] == \"tp\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])\n  |> sort(columns: [\"_time\"])"
    },
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat_pid\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rp\" or r[\"_field\"] == \"tp\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn:(r) => r[\"element_name\"] != \"\")"
    }
   ]
  },
  { "title": "System netstat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total received buffer size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat\")\n  |> filter(fn: (r) => r[\"type\"] == \"ConnectionDetectionEvent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"recv_buffer_size\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    }
   ]
  },
  {
   "title": "Total used buffer size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat\")\n  |> filter(fn: (r) => r[\"type\"] == \"ConnectionDetectionEvent\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"recv_buffer_used\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    }
   ]
  },
  {
   "title": "Total transfered bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat\")\n  |> filter(fn: (r) => r[\"type\"] == \"ConnectionUpdateEvent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_bytes\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    },
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat\")\n  |> filter(fn: (r) => r[\"type\"] == \"ConnectionUpdateEvent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tx_bytes\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn:(r) => r[\"element_name\"] != \"\")"
    }
   ]
  },
  {
   "title": "Total received bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat\")\n  |> filter(fn: (r) => r[\"type\"] == \"ConnectionUpdateEvent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_bytes\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    },
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat\")\n  |> filter(fn: (r) => r[\"type\"] == \"ConnectionUpdateEvent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_bytes\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn:(r) => r[\"element_name\"] != \"\")"
    }
   ]
  },
  {
   "title": "Total received packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat\")\n  |> filter(fn: (r) => r[\"type\"] == \"ConnectionUpdateEvent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_packets\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> drop(columns:[\"element_name\", \"event_type\"])"
    },
    {
     "query": "from(bucket: \"performance-carina\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Netstat\")\n  |> filter(fn: (r) => r[\"type\"] == \"ConnectionUpdateEvent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_packets\")\n  |> filter(fn: (r) => r[\"device_name\"] == \"${device_name}\")\n  |> filter(fn: (r) => r[\"flow_id\"] == \"${flow_id}\")\n  |> filter(fn: (r) => r[\"os_version\"] == \"${os_version}\")\n  |> filter(fn:(r) => r[\"element_name\"] != \"\")"
    }
   ]
  }
 ]
}