version: "3"

networks:
  performance:

services:
  influxdb:
    image: influxdb:2.3.0
    ports:
      - "8086:8086"
    networks:
      - performance

  grafana:
    image: grafana/grafana:9.0.4
    ports:
      - "3000:3000"
    networks:
      - performance
